[workspace]
members = [
    "crates/rsi_ml_core",
    "crates/rsi_ml_autograd",
    "crates/rsi_ml_ops",
    "crates/rsi_ml",
    "crates/rsi_ml_optim",
]
resolver = "2"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
